<Project>
  <PropertyGroup>
    <!-- Enable central package management,
        https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Stride.CommunityToolkit" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolKit.Bepu" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolKit.Bullet" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolkit.Skyboxes" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolkit.Windows" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolkit.DebugShapes" Version="1.0.0-preview.58" />
    <PackageVersion Include="Stride.CommunityToolkit.ImGui" Version="1.0.0-preview.58" />

    <PackageVersion Include="NexVYaml" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Build" Version="17.13.9" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.13.9" />

    <PackageVersion Include="ImGui.NET" Version="1.91.6.1" />

    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.4" />
    <PackageVersion Include="Hexa.NET.ImGuizmo" Version="2.2.4" />
    <PackageVersion Include="Hexa.NET.ImNodes" Version="2.2.4" />
    <PackageVersion Include="Hexa.NET.ImPlot" Version="2.2.4" />

  </ItemGroup>
</Project>